//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/step_2/InputActions_ActionMaps.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActions_ActionMaps: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActions_ActionMaps()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActions_ActionMaps"",
    ""maps"": [
        {
            ""name"": ""ActionMapsSlimeA"",
            ""id"": ""981e11d5-a1f4-4b70-a944-a399847a25e3"",
            ""actions"": [
                {
                    ""name"": ""DoMoveForwardAxis"",
                    ""type"": ""Value"",
                    ""id"": ""82b4416b-8127-4413-81f7-702e99c6f303"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""DoMoveRotate"",
                    ""type"": ""Value"",
                    ""id"": ""4ec642b6-3b7f-49be-a4ab-8a8097ece1a2"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""DoFire"",
                    ""type"": ""Button"",
                    ""id"": ""f5b3d0fc-ecc5-48b4-a3dd-16b2304c588f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WS"",
                    ""id"": ""09d7cf1c-f7ae-4dce-8843-747bc7f02faa"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DoMoveForwardAxis"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""1cef216b-2b54-4266-9fd4-91548568dfa7"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DoMoveForwardAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""7f089d51-8882-4245-b564-ce44c34182da"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DoMoveForwardAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""DA"",
                    ""id"": ""2ce02c09-4d65-4529-a152-8e8852e7a377"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DoMoveRotate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""f644914d-4bec-490f-af8c-26158b608ec8"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DoMoveRotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""733ac70b-3a6c-482f-928a-528f2305ac94"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DoMoveRotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""6f063437-7108-4353-b9ff-c6e4e137e4c7"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DoFire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""ActionMapsSlimeB"",
            ""id"": ""20819330-aba9-4687-9ad1-0ec339391bbd"",
            ""actions"": [
                {
                    ""name"": ""DoMoveForwardAxis"",
                    ""type"": ""Value"",
                    ""id"": ""1d350558-a776-4529-baa0-7ef1abc05e33"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""DoMoveRotate"",
                    ""type"": ""Value"",
                    ""id"": ""9bbc4425-4dcb-49cf-aeea-f4d653a688e6"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""DoFire"",
                    ""type"": ""Button"",
                    ""id"": ""766d4e68-c2d9-4f7c-abfc-e466f6d2f021"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WS"",
                    ""id"": ""82d8b17c-beb8-4ffa-837d-ffd2850cd6ea"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DoMoveForwardAxis"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""4dbcd28e-f26c-469b-9c77-15114a1dfea2"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DoMoveForwardAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""de953042-7a71-4ffa-b6f5-bea7441f95bc"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DoMoveForwardAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""DA"",
                    ""id"": ""28c4c26e-4bfb-4909-a08e-dac14e13dda2"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DoMoveRotate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""e21fe51f-e6fd-4a37-afd4-294f016ae265"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DoMoveRotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""1712ae37-18a3-4b67-ad18-76909755fe27"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DoMoveRotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""e2ce4058-2739-4b6f-8949-56eef3ef39b1"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DoFire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""InputActions_ActionMaps"",
            ""bindingGroup"": ""InputActions_ActionMaps"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // ActionMapsSlimeA
        m_ActionMapsSlimeA = asset.FindActionMap("ActionMapsSlimeA", throwIfNotFound: true);
        m_ActionMapsSlimeA_DoMoveForwardAxis = m_ActionMapsSlimeA.FindAction("DoMoveForwardAxis", throwIfNotFound: true);
        m_ActionMapsSlimeA_DoMoveRotate = m_ActionMapsSlimeA.FindAction("DoMoveRotate", throwIfNotFound: true);
        m_ActionMapsSlimeA_DoFire = m_ActionMapsSlimeA.FindAction("DoFire", throwIfNotFound: true);
        // ActionMapsSlimeB
        m_ActionMapsSlimeB = asset.FindActionMap("ActionMapsSlimeB", throwIfNotFound: true);
        m_ActionMapsSlimeB_DoMoveForwardAxis = m_ActionMapsSlimeB.FindAction("DoMoveForwardAxis", throwIfNotFound: true);
        m_ActionMapsSlimeB_DoMoveRotate = m_ActionMapsSlimeB.FindAction("DoMoveRotate", throwIfNotFound: true);
        m_ActionMapsSlimeB_DoFire = m_ActionMapsSlimeB.FindAction("DoFire", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // ActionMapsSlimeA
    private readonly InputActionMap m_ActionMapsSlimeA;
    private List<IActionMapsSlimeAActions> m_ActionMapsSlimeAActionsCallbackInterfaces = new List<IActionMapsSlimeAActions>();
    private readonly InputAction m_ActionMapsSlimeA_DoMoveForwardAxis;
    private readonly InputAction m_ActionMapsSlimeA_DoMoveRotate;
    private readonly InputAction m_ActionMapsSlimeA_DoFire;
    public struct ActionMapsSlimeAActions
    {
        private @InputActions_ActionMaps m_Wrapper;
        public ActionMapsSlimeAActions(@InputActions_ActionMaps wrapper) { m_Wrapper = wrapper; }
        public InputAction @DoMoveForwardAxis => m_Wrapper.m_ActionMapsSlimeA_DoMoveForwardAxis;
        public InputAction @DoMoveRotate => m_Wrapper.m_ActionMapsSlimeA_DoMoveRotate;
        public InputAction @DoFire => m_Wrapper.m_ActionMapsSlimeA_DoFire;
        public InputActionMap Get() { return m_Wrapper.m_ActionMapsSlimeA; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ActionMapsSlimeAActions set) { return set.Get(); }
        public void AddCallbacks(IActionMapsSlimeAActions instance)
        {
            if (instance == null || m_Wrapper.m_ActionMapsSlimeAActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ActionMapsSlimeAActionsCallbackInterfaces.Add(instance);
            @DoMoveForwardAxis.started += instance.OnDoMoveForwardAxis;
            @DoMoveForwardAxis.performed += instance.OnDoMoveForwardAxis;
            @DoMoveForwardAxis.canceled += instance.OnDoMoveForwardAxis;
            @DoMoveRotate.started += instance.OnDoMoveRotate;
            @DoMoveRotate.performed += instance.OnDoMoveRotate;
            @DoMoveRotate.canceled += instance.OnDoMoveRotate;
            @DoFire.started += instance.OnDoFire;
            @DoFire.performed += instance.OnDoFire;
            @DoFire.canceled += instance.OnDoFire;
        }

        private void UnregisterCallbacks(IActionMapsSlimeAActions instance)
        {
            @DoMoveForwardAxis.started -= instance.OnDoMoveForwardAxis;
            @DoMoveForwardAxis.performed -= instance.OnDoMoveForwardAxis;
            @DoMoveForwardAxis.canceled -= instance.OnDoMoveForwardAxis;
            @DoMoveRotate.started -= instance.OnDoMoveRotate;
            @DoMoveRotate.performed -= instance.OnDoMoveRotate;
            @DoMoveRotate.canceled -= instance.OnDoMoveRotate;
            @DoFire.started -= instance.OnDoFire;
            @DoFire.performed -= instance.OnDoFire;
            @DoFire.canceled -= instance.OnDoFire;
        }

        public void RemoveCallbacks(IActionMapsSlimeAActions instance)
        {
            if (m_Wrapper.m_ActionMapsSlimeAActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IActionMapsSlimeAActions instance)
        {
            foreach (var item in m_Wrapper.m_ActionMapsSlimeAActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ActionMapsSlimeAActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ActionMapsSlimeAActions @ActionMapsSlimeA => new ActionMapsSlimeAActions(this);

    // ActionMapsSlimeB
    private readonly InputActionMap m_ActionMapsSlimeB;
    private List<IActionMapsSlimeBActions> m_ActionMapsSlimeBActionsCallbackInterfaces = new List<IActionMapsSlimeBActions>();
    private readonly InputAction m_ActionMapsSlimeB_DoMoveForwardAxis;
    private readonly InputAction m_ActionMapsSlimeB_DoMoveRotate;
    private readonly InputAction m_ActionMapsSlimeB_DoFire;
    public struct ActionMapsSlimeBActions
    {
        private @InputActions_ActionMaps m_Wrapper;
        public ActionMapsSlimeBActions(@InputActions_ActionMaps wrapper) { m_Wrapper = wrapper; }
        public InputAction @DoMoveForwardAxis => m_Wrapper.m_ActionMapsSlimeB_DoMoveForwardAxis;
        public InputAction @DoMoveRotate => m_Wrapper.m_ActionMapsSlimeB_DoMoveRotate;
        public InputAction @DoFire => m_Wrapper.m_ActionMapsSlimeB_DoFire;
        public InputActionMap Get() { return m_Wrapper.m_ActionMapsSlimeB; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ActionMapsSlimeBActions set) { return set.Get(); }
        public void AddCallbacks(IActionMapsSlimeBActions instance)
        {
            if (instance == null || m_Wrapper.m_ActionMapsSlimeBActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ActionMapsSlimeBActionsCallbackInterfaces.Add(instance);
            @DoMoveForwardAxis.started += instance.OnDoMoveForwardAxis;
            @DoMoveForwardAxis.performed += instance.OnDoMoveForwardAxis;
            @DoMoveForwardAxis.canceled += instance.OnDoMoveForwardAxis;
            @DoMoveRotate.started += instance.OnDoMoveRotate;
            @DoMoveRotate.performed += instance.OnDoMoveRotate;
            @DoMoveRotate.canceled += instance.OnDoMoveRotate;
            @DoFire.started += instance.OnDoFire;
            @DoFire.performed += instance.OnDoFire;
            @DoFire.canceled += instance.OnDoFire;
        }

        private void UnregisterCallbacks(IActionMapsSlimeBActions instance)
        {
            @DoMoveForwardAxis.started -= instance.OnDoMoveForwardAxis;
            @DoMoveForwardAxis.performed -= instance.OnDoMoveForwardAxis;
            @DoMoveForwardAxis.canceled -= instance.OnDoMoveForwardAxis;
            @DoMoveRotate.started -= instance.OnDoMoveRotate;
            @DoMoveRotate.performed -= instance.OnDoMoveRotate;
            @DoMoveRotate.canceled -= instance.OnDoMoveRotate;
            @DoFire.started -= instance.OnDoFire;
            @DoFire.performed -= instance.OnDoFire;
            @DoFire.canceled -= instance.OnDoFire;
        }

        public void RemoveCallbacks(IActionMapsSlimeBActions instance)
        {
            if (m_Wrapper.m_ActionMapsSlimeBActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IActionMapsSlimeBActions instance)
        {
            foreach (var item in m_Wrapper.m_ActionMapsSlimeBActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ActionMapsSlimeBActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ActionMapsSlimeBActions @ActionMapsSlimeB => new ActionMapsSlimeBActions(this);
    private int m_InputActions_ActionMapsSchemeIndex = -1;
    public InputControlScheme InputActions_ActionMapsScheme
    {
        get
        {
            if (m_InputActions_ActionMapsSchemeIndex == -1) m_InputActions_ActionMapsSchemeIndex = asset.FindControlSchemeIndex("InputActions_ActionMaps");
            return asset.controlSchemes[m_InputActions_ActionMapsSchemeIndex];
        }
    }
    public interface IActionMapsSlimeAActions
    {
        void OnDoMoveForwardAxis(InputAction.CallbackContext context);
        void OnDoMoveRotate(InputAction.CallbackContext context);
        void OnDoFire(InputAction.CallbackContext context);
    }
    public interface IActionMapsSlimeBActions
    {
        void OnDoMoveForwardAxis(InputAction.CallbackContext context);
        void OnDoMoveRotate(InputAction.CallbackContext context);
        void OnDoFire(InputAction.CallbackContext context);
    }
}
